language: node_js
node_js:
  - '0.10'
before_script:
  - npm install -g bower grunt-cli
  - bower install
services: mongodb
after_success:
  - bash ./.travis/after_success.sh
# env:
#   global:
#     secure: "N327OhfaWIiaWkIuTkyztNWJoYq/bQ2VxAKs2IUiYdnPaappeRKxykEK4aLmdIx4QsaND0XanzMvO/hBHl8ueiPgM1ztgiMgIEXtD8PMRsoJI3QiuF4pvqluazGCsbj5lmvY/bbAk8OMlo4NP5+10pragu2lk9cekIrsINpu7lI="
